# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  example.com:
    site_hosts:
      - canonical: 67.205.150.210
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@67.205.150.210
    repo: git@github.com:chznbaum/example.com.git
    repo_subtree_path: site
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    env:
      wp_siteurl: ${WP_HOME}